# Generated by Django 3.1.7 on 2021-08-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('change_message', models.TextField()),
                ('action_flag', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MClndr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clndr_dt', models.DateField(blank=True, db_column='CLNDR_DT', null=True)),
                ('pj_no', models.CharField(blank=True, db_column='PJ_NO', max_length=8, null=True)),
                ('wrk_dt_kbn', models.CharField(blank=True, db_column='WRK_DT_KBN', max_length=2, null=True)),
            ],
            options={
                'db_table': 'M_CLNDR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MPjKnr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pj_no', models.TextField(blank=True, db_column='PJ_NO', null=True)),
                ('pj_nm', models.TextField(blank=True, db_column='PJ_NM', null=True)),
                ('pj_st_time', models.DateField(blank=True, db_column='PJ_ST_TIME', null=True)),
                ('rst_st_time', models.DateField(blank=True, db_column='RST_ST_TIME', null=True)),
                ('rst_ed_time', models.DateField(blank=True, db_column='RST_ED_TIME', null=True)),
                ('pj_ed_time', models.DateField(blank=True, db_column='PJ_ED_TIME', null=True)),
                ('act_hrs', models.TextField(blank=True, db_column='ACT_HRS', null=True)),
            ],
            options={
                'db_table': 'M_PJ_KNR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MPjSzk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syn_cd', models.CharField(blank=True, db_column='SYN_CD', max_length=6, null=True)),
                ('pj_kbn', models.CharField(blank=True, db_column='PJ_KBN', max_length=2, null=True)),
                ('pj_no', models.CharField(blank=True, db_column='PJ_NO', max_length=8, null=True)),
            ],
            options={
                'db_table': 'M_PJ_SZK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MUsr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syn_cd', models.CharField(blank=True, db_column='SYN_CD', max_length=6, null=True)),
                ('syn_nm_s_kj', models.TextField(blank=True, db_column='SYN_NM_S_KJ', null=True)),
                ('syn_nm_n_kj', models.TextField(blank=True, db_column='SYN_NM_N_KJ', null=True)),
                ('syn_nm_s_kn', models.TextField(blank=True, db_column='SYN_NM_S_KN', null=True)),
                ('syn_nm_n_kn', models.TextField(blank=True, db_column='SYN_NM_N_KN', null=True)),
                ('nysy_dt', models.DateField(blank=True, db_column='NYSY_DT', null=True)),
                ('pj_add_dt', models.DateField(blank=True, db_column='PJ_ADD_DT', null=True)),
                ('pj_del_dt', models.DateField(blank=True, db_column='PJ_DEL_DT', null=True)),
                ('e_mail_adr', models.TextField(blank=True, db_column='E_MAIL_ADR', null=True)),
                ('syn_kngn', models.CharField(blank=True, db_column='SYN_KNGN', max_length=2, null=True)),
                ('lgn_pss', models.TextField(blank=True, db_column='LGN_PSS', null=True)),
                ('syn_kbn', models.CharField(blank=True, db_column='SYN_KBN', max_length=2, null=True)),
            ],
            options={
                'db_table': 'M_USR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TKnti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syn_cd', models.CharField(blank=True, db_column='SYN_CD', max_length=6, null=True)),
                ('knti_dt', models.DateField(blank=True, db_column='KNTI_DT', null=True)),
                ('ido_kbn', models.CharField(blank=True, db_column='IDO_KBN', max_length=1, null=True)),
                ('pj_no', models.TextField(blank=True, db_column='PJ_NO', null=True)),
                ('rmrks', models.TextField(blank=True, db_column='RMRKS', null=True)),
            ],
            options={
                'db_table': 'T_KNTI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TKntiDtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syn_cd', models.CharField(blank=True, db_column='SYN_CD', max_length=6, null=True)),
                ('knti_dt', models.DateField(blank=True, db_column='KNTI_DT', null=True)),
                ('pj_no', models.CharField(blank=True, db_column='PJ_NO', max_length=8, null=True)),
                ('wrk_st_time', models.DateField(blank=True, db_column='WRK_ST_TIME', null=True)),
                ('wrk_ed_time', models.DateField(blank=True, db_column='WRK_ED_TIME', null=True)),
                ('act_hrs', models.TextField(blank=True, db_column='ACT_HRS', null=True)),
                ('rst_hrs', models.TextField(blank=True, db_column='RST_HRS', null=True)),
                ('mdnght_wrk_hrs', models.TextField(blank=True, db_column='MDNGHT_WRK_HRS', null=True)),
                ('nn_rglr_wrk_hrs', models.TextField(blank=True, db_column='NN_RGLR_WRK_HRS', null=True)),
            ],
            options={
                'db_table': 'T_KNTI_DTL',
                'managed': False,
            },
        ),
    ]
